pagination:
  page_size: 10
  activity_log:
    page_size: 5
date_format: "%d-%m-%Y"
user_books:
  unread: mark_unread
  read: mark_read
  reading: mark_reading
  favored: add_to_favorites
  unfavored: remove_from_favorites
books:
  search: search
activities:
  read: mark_as_read
  reading: mark_as_reading
  favored: add_to_favorites
  follow: follow
  followed: followed
  review: review
  comment: comment
users:
  favorite_books: favorite_books
  reading_history: reading_history
  timeline: timeline
  edit: "edit"
  requests: "requests"
